import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

sfp_roc_data = pd.read_csv('sfp_specific_roc_data.csv')
plt.figure()
plt.plot(sfp_roc_data['x'], sfp_roc_data['y'])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Sfp')
plt.savefig('sfp_specific_roc.pdf')


acps_roc_data = pd.read_csv('acps_specific_roc_data.csv')
plt.figure()
plt.plot(acps_roc_data['x'], acps_roc_data['y'])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('AcpS')
plt.savefig('acps_specific_roc.pdf')


sfp_quality = pd.read_csv('sfp_specific_simulation_quality.csv')
plt.figure()
plt.plot(1+np.arange(len(sfp_quality)), sfp_quality['pool'], label='POOL')
plt.plot(1+np.arange(len(sfp_quality)), sfp_quality['mutate'], label='Mutation')
plt.plot(1+np.arange(len(sfp_quality)), sfp_quality['predict_optimize'], label='Predict-then-Optimize')
plt.legend()
plt.title('Sfp specific hits simulation quality')
plt.xlabel('# of peptides recommended')
plt.ylabel('Probability of Improvement')
plt.savefig('sfp_specific_simulation_quality.pdf')

acps_quality = pd.read_csv('acps_specific_simulation_quality.csv')
plt.figure()
plt.plot(1+np.arange(len(acps_quality)), acps_quality['pool'], label='POOL')
plt.plot(1+np.arange(len(acps_quality)), acps_quality['mutate'], label='Mutation')
plt.plot(1+np.arange(len(acps_quality)), acps_quality['predict_optimize'], label='Predict-then-Optimize')
plt.legend()
plt.title('AcpS specific hits simulation quality')
plt.xlabel('# of peptides recommended')
plt.ylabel('Probability of Improvement')
plt.savefig('acps_specific_simulation_quality.pdf')

coord = pd.read_csv('sfp_specific_simulation_coord.csv')
plt.figure()
plt.plot(coord['x'].values[:100], coord['y'].values[:100], '*', label='POOL')
plt.plot(coord['x'].values[100:200], coord['y'].values[100:200], '*', label='Mutation')
plt.plot(coord['x'].values[200:300], coord['y'].values[200:300], '*', label='Predict-then-Optimize')
plt.plot(coord['x'].values[300:], coord['y'].values[300:], '*', label='Train Data')
plt.legend()
plt.xlabel('x')
plt.ylabel('y')
plt.title('Sfp specific hits simulation coordinates')
plt.savefig('sfp_specific_simulation_coord.pdf')

coord = pd.read_csv('acps_specific_simulation_coord.csv')
plt.figure()
plt.plot(coord['x'].values[:100], coord['y'].values[:100], '*', label='POOL')
plt.plot(coord['x'].values[100:200], coord['y'].values[100:200], '*', label='Mutation')
plt.plot(coord['x'].values[200:300], coord['y'].values[200:300], '*', label='Predict-then-Optimize')
plt.plot(coord['x'].values[300:], coord['y'].values[300:], '*', label='Train Data')
plt.legend()
plt.xlabel('x')
plt.ylabel('y')
plt.title('AcpS specific hits simulation coordinates')
plt.savefig('acps_specific_simulation_coord.pdf')
